version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: boardgames_db
    environment:
      POSTGRES_USER: loft_admin
      POSTGRES_PASSWORD: loft_password
      POSTGRES_DB: loft_rental
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: loft_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@loft.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  pgdata: